### ISSUE TITLE
Missing abundant trypsin peptides in my search

### ISSUE THREAD

**Issue by ashleyives** [vdemichev/DiaNN#1390]
Hi Vadim, 

I am running single cell data through DiaNN 1.9 and 2.0. DiaNN is not detecting/ reporting several trypsin peptides in the parquet.report. I've manually validated that these peptides exist in skyline and the CVs are low across my runs. I'm concerned about this missing data given these peptides are quiet abundant. 

My general pipeline is 1) generating an in silico library against a FASTA, 2) searching high-input samples (e.g. samples with 50+ cells) against this first library, and then 3) searching my single cell runs against the library generated in step 2. I've also tried searching my single cell runs against the FASTA directly with MBR turned on. 

Raising the FDR in step 2 from 1% to 5% did seem to help this issue, but there were still many files with missing trypsin peptides. 

I've attached the log files for steps 1-3. 

Thank you so much!
ash 

[step1_report-lib.log.txt](https://github.com/user-attachments/files/18740006/step1_report-lib.log.txt)
[step3_report.log.txt](https://github.com/user-attachments/files/18740007/step3_report.log.txt)
[step2_report.log.txt](https://github.com/user-attachments/files/18740005/step2_report.log.txt)

**Comment by vdemichev** [comment]
Hi Ashley,

Logs seem fine overall, just some general comments:
- Mass accuracies are fixed to 20ppm, this is likely very suboptimal for these runs (DIA-NN recomments 3ppm-4ppm for MS1).
- MBR is off, i.e. this is not recommended for quantitative analyses, with MBR missing value rate will be reduced very significantly.

Can you please try analysing with MBR and set mass accuracies as in https://github.com/vdemichev/DiaNN?tab=readme-ov-file#changing-default-settings (we have updated the docs with the release of 2.0)?

If still cannot detect a particular peptide in certain run, can you please share the .predicted.speclib and such a run (just a single one) and I take a look?

Best,
Vadim

**Comment by ashleyives** [comment]
Can do, thank you so much! Will try this ASAP and report back.

**Comment by ashleyives** [comment]
Hi Vadim, 

Still running my files, but just wanted to clarify something. 
"If still cannot detect a particular peptide in certain run, can you please share the .predicted.speclib and such a run (just a single one) and I take a look?" 
Did you mean share the .raw file with you? What's the most convenient way to do that? 

Thanks again (:

**Comment by vdemichev** [comment]
Yes, please just upload to any convenient storage location (OneDrive, Google Drive, etc).

**Comment by ashleyives** [comment]
The suggested search did not seem to resolve the issue. If you want to focus on one precursor in particular I would suggest VATVSLPR2. 

https://drive.google.com/drive/folders/1D-Xq5UWRgmeGCgDfTumRZ8AGLxIo-rZW?usp=drive_link

.raw files, FASTA, and predicted spec lib enclosed. Thank you!

**Comment by vdemichev** [comment]
I've sent access request

**Comment by ashleyives** [comment]
Access granted, thank you again!

**Comment by vdemichev** [comment]
Hi Ashley,

I seem to detect this peptides in both runs with both 1.9.2 and 2.0.2 - if I use a contaminant-only library (could not extract the .speclib, the zip file seems broken). Are the peptides still missing when you run DIA-NN with MBR or a DIA-based empirical library it creates from the data?

Best,
Vadim

**Comment by ashleyives** [comment]
Hi Vadim, 

Thank you for investigating this! I haven't had time to circle back yet but will give your suggestions a try ASAP. Thanks again, ash
