### ISSUE TITLE
Decoy sequence format?

### ISSUE THREAD

**Issue by daichengxin** [vdemichev/DiaNN#1404]
Hi @vdemichev , When I running DIA-NN 2.0 and export decoys, the report show these sequence with "^", but some sequence don't have "^". So What does that "^" mean?

![Image](https://github.com/user-attachments/assets/d3f10992-a29d-4b54-bb6d-a3e0055a2463)

**Comment by vdemichev** [comment]
Hi,

This is an unintended artifact of parquet to parquet library export, was fixed in 2.0.1.

Best,
Vadim

**Comment by daichengxin** [comment]
Hi @vdemichev , I tested DIA-NN 2.0.1 and 2.0.2, and the problem still exists.

**Comment by vdemichev** [comment]
Can you please share the log and indicate at which file you are looking at?

**Comment by daichengxin** [comment]
I am looking at report.parquet file. 

```
DIA-NN 2.0.2 Academia  (Data-Independent Acquisition by Neural Networks)
Compiled on Feb 14 2025 08:36:32
Current date and time: Wed Feb 19 06:53:39 2025
Logical CPU cores: 112
Thread number set to 8
Scan windows will be inferred separately for different runs
A fast algorithm will be used to select the MS2 mass accuracy setting
Mass accuracy will be determined separately for different runs
Heuristic protein grouping will be used, to reduce the number of protein groups obtained; this mode is recommended for benchmarking protein ID numbers, GO/pathway and system-scale analyses
Implicit protein grouping: genes; this determines which peptides are considered 'proteotypic' and thus affects protein FDR calculation
Existing .quant files will be used
Precursor/protein x samples expression level matrices will be saved along with the main report
Output will be filtered at 0.01 FDR
XICs within 10 seconds from the apex will be extracted for each precursor and saved in .parquet format, a folder will be created next to the main report for the XICs storage
DIA-NN will automatically optimise the mass accuracy for each acquisition, use this mode only to determine the approximate optimal settings
WARNING: combining reuse of .quant files with automatic optimisation of mass accuracies or scan window will lead to results that are different from those of the original analysis that produced the .quant files and is strongly not recommended

4 files will be processed
[0:00] Loading spectral library empirical_library.parquet
[0:00] Reading 2 row groups
[0:00] Spectral library loaded: 1542 protein isoforms, 1538 protein groups and 6719 precursors in 5648 elution groups.
[0:00] Loading protein annotations from FASTA REF_EColi_K12_UPS1_combined.fasta
[0:00] Annotating library proteins with information from the FASTA database
[0:00] Gene names missing for some isoforms
[0:00] Library contains 1540 proteins, and 1540 genes
[0:00] Initialising library
[0:00] Library RAM: 0MB (core), 1MB (fragments), 0MB (names), 0MB (protein_ids), 0MB (proteins)
[0:00] Saving the library to empirical_library.parquet.skyline.speclib
[0:00] Cross-run analysis
[0:00] Reading quantification information: 4 files
[0:00] Averaged recommended settings for this experiment: Mass accuracy = 15ppm, MS1 accuracy = 20ppm, Scan window = 8
[0:00] Quantifying peptides
WARNING: QuantUMS requires 6 or more runs for the optimisation of its hyperparameters to perform best.
[0:11] Quantification parameters: 0.247303, 0.00657298, 0.00223354, 0.0116004, 0.013897, 0.0128857, 0.101719, 0.0481319, 0.0490518, 0.0130862, 0.0478859, 0.0342254, 0.178583, 0.0501698, 0.0544673, 0.0112187
[0:14] Assembling protein groups
[0:14] Quantifying proteins
[0:14] Calculating q-values for protein and gene groups
[0:14] Calculating global q-values for protein and gene groups
[0:14] Protein groups with global q-value <= 0.01: 1445
[0:14] Compressed report saved to diann_report.parquet. Use R 'arrow' or Python 'PyArrow' package to process
[0:14] Saving precursor levels matrix
[0:14] Precursor levels matrix (1% precursor and protein group FDR) saved to diann_report.pr_matrix.tsv.
[0:14] Saving protein group levels matrix
[0:14] Protein groups matrix saved to diann_report.pg_matrix.tsv.
[0:14] Saving gene group levels matrix
[0:14] Gene groups matrix saved to diann_report.gg_matrix.tsv.
[0:14] Saving unique genes levels matrix
[0:14] Unique genes matrix saved to diann_report.unique_genes_matrix.tsv.
[0:14] Manifest saved to diann_report.manifest.txt
[0:14] Stats report saved to diann_report.stats.tsv

The following warnings or errors (in alphabetic order) were detected at least the indicated number of times:
WARNING: QuantUMS requires 6 or more runs for the optimisation of its hyperparameters to perform best. : 1
WARNING: combining reuse of .quant files with automatic optimisation of mass accuracies or scan window will lead to results that are different from those of the original analysis that produced the .quant files and is strongly not recommended : 1
Finished


How to cite:
using DIA-NN: Demichev et al, Nature Methods, 2020, https://www.nature.com/articles/s41592-019-0638-x
analysing Scanning SWATH: Messner et al, Nature Biotechnology, 2021, https://www.nature.com/articles/s41587-021-00860-4
analysing PTMs: Steger et al, Nature Communications, 2021, https://www.nature.com/articles/s41467-021-25454-1
analysing dia-PASEF: Demichev et al, Nature Communications, 2022, https://www.nature.com/articles/s41467-022-31492-0
analysing Slice-PASEF: Szyrwiel et al, biorxiv, 2022, https://doi.org/10.1101/2022.10.31.514544
plexDIA / multiplexed DIA: Derks et al, Nature Biotechnology, 2023, https://www.nature.com/articles/s41587-022-01389-w
CysQuant: Huang et al, Redox Biology, 2023, https://doi.org/10.1016/j.redox.2023.102908
using QuantUMS: Kistner at al, biorxiv, 2023, https://doi.org/10.1101/2023.06.20.545604
[0:14] Log saved to diann_report.log.txt
```

**Comment by vdemichev** [comment]
Can you please share the full log? This is needed to see the settings used.

**Comment by daichengxin** [comment]
Thanks a lot. I see
